version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
permissions: 
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777
hooks:
  ApplicationStart:
    - location : scripts/start_server
      timeout: 300
      runas: ubuntu
