version: 0.0
os: linux
files:
  - source: //home/ubuntu/streamlit-app
    destination: /home/ubuntu/streamlit-app
permissions: 
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777

hooks:
  ApplicationStart:
    - Location : scripts/start_server
      timeout: 300
      runas: ubuntu

  
