version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/streamlit-app
permissions: 
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777

hooks:

  ApplicationStart:
    - Location : startsevice.sh
      timeout: 300
      runas: ubuntu

  